#!/usr/bin/env python3
"""XKB key names -> src/input/key_table.odin, numbered in SDL scancodes.

The output is COMMITTED, same rule as gen-unicode.py: generated Odin folds into .rodata and
nothing parses at startup.

    tools/gen-keys.py src/input/key_table.odin

The names come from xkeyboard-config's evdev keycodes file, the canonical map between
physical key positions and XKB names (<AC06> and friends). The numbers are SDL scancodes,
the kernel's one canonical code space: SDL hands exactly these on every backend and every
platform, so no per-platform crossmapping table ever lands. The bridge is SDL's own
evdev-to-scancode table, so both sides of every key agree by construction: XKB name ->
X keycode - 8 = evdev -> SDL scancode. A position SDL has no scancode for is a key SDL
will never deliver, and it is dropped rather than carried.

Run after download-deps.sh: the SDL tables are read out of vendor/sdl3-src.
"""
import os, re, sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
XKB = "/usr/share/X11/xkb/keycodes/evdev"
SDL_LINUX = os.path.join(REPO, "vendor/sdl3-src/src/events/scancodes_linux.h")
SDL_SCAN = os.path.join(REPO, "vendor/sdl3-src/include/SDL3/SDL_scancode.h")


def read(path, hint):
    try:
        return open(path).read()
    except FileNotFoundError:
        sys.exit(f"{path} not found — {hint}")


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    xkb = read(XKB, "install xkeyboard-config, or fetch\n"
               "https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/"
               "-/raw/master/keycodes/evdev")
    scan = read(SDL_SCAN, "run download-deps.sh first")
    linux = read(SDL_LINUX, "run download-deps.sh first")

    # SDL scancode name -> number.
    values = {n: int(v) for n, v in re.findall(r"SDL_SCANCODE_(\w+) = (\d+)", scan)}

    # evdev code -> SDL scancode number, from the order of SDL's own table.
    body = linux.split("linux_scancode_table[]", 1)[1]
    table = [values.get(n, 0) for n in re.findall(r"SDL_SCANCODE_(\w+)", body)]

    def sdl_of(xcode):
        ev = xcode - 8
        return table[ev] if 0 <= ev < len(table) else 0

    codes = {}   # XKB name -> SDL scancode, keys SDL cannot deliver dropped
    for name, num in re.findall(r"<(\w+)>\s*=\s*(\d+);", xkb):
        code = sdl_of(int(num))
        if code and name not in codes:
            codes[name] = code
    aliases = {}  # alias -> primary name
    for alias, target in re.findall(r"alias\s+<(\w+)>\s*=\s*<(\w+)>;", xkb):
        if target in codes:
            aliases.setdefault(alias, target)

    by_code = {}  # code -> primary name, first assignment wins; aliases never primary
    for name, code in codes.items():
        by_code.setdefault(code, name)

    pairs = sorted({**{a: codes[t] for a, t in aliases.items()}, **codes}.items())

    with open(sys.argv[1], "w") as f:
        f.write("package input\n\n"
                "// GENERATED by tools/gen-keys.py: XKB names over SDL scancodes.\n"
                "// Do not edit. Committed, so a fresh clone builds without running any tool.\n"
                "\n"
                "// Primary XKB name per code, sorted by code, for display.\n"
                "@(rodata)\n"
                f"KEY_NAMES := [{len(by_code)}]struct {{\n"
                "    code: Code,\n"
                "    name: string,\n"
                "} {\n")
        for code in sorted(by_code):
            f.write(f'    {{{code}, "{by_code[code]}"}},\n')
        f.write("}\n\n"
                "// Every name and alias, sorted by name, for the config-spelling lookup.\n"
                "@(rodata)\n"
                f"KEY_CODES := [{len(pairs)}]struct {{\n"
                "    name: string,\n"
                "    code: Code,\n"
                "} {\n")
        for name, code in pairs:
            f.write(f'    {{"{name}", {code}}},\n')
        f.write("}\n")

    print(f"  {len(by_code)} codes, {len(pairs)} names -> {sys.argv[1]}")


if __name__ == "__main__":
    main()
