#!/usr/bin/env python3
"""Generate the syntax plugin's language registry from Helix's languages.toml.

A grammar is a name, a git repo, a pinned rev and the extensions that select it.
Hand-curating three hundred of those is not work worth doing twice, so this pulls
Helix's languages.toml (pinned to a commit) and relabels it. Helix is MPL-2.0 and
this is a reformatted name -> repo -> extensions mapping, attributed below.

The output is a C header COMMITTED to the repo, for the same reason the generated
width tables are: a fresh clone must build the plugin without running this first.
Grammars themselves are not vendored — the picker's `enter` row builds one with
tools/oket-grammar at runtime, which is what keeps a release small.
"""

import sys
import tomllib
import urllib.request

# Pinned Helix ref — bump to refresh the registry, then re-run this.
#
# A COMMIT rather than a release tag, deliberately: Helix cuts releases roughly twice a year
# and its languages.toml gains grammars continuously between them. A sha is exactly as
# reproducible as a tag, it just is not as readable, which is what HELIX_LABEL is for.
HELIX_REF = "079a789e8cb08ead67f19e1971a1b7438b37354b"
HELIX_LABEL = "master @ 2026-07-23"
LANGUAGES_TOML_URL = (
    f"https://raw.githubusercontent.com/helix-editor/helix/{HELIX_REF}/languages.toml"
)


def fetch_languages_toml() -> dict:
    # Timeout so a stalled network cannot hang a build indefinitely.
    with urllib.request.urlopen(LANGUAGES_TOML_URL, timeout=30) as resp:
        return tomllib.loads(resp.read().decode("utf-8"))


def build_registry(doc: dict) -> list[dict]:
    # grammar name -> its git source; only git-sourced grammars are installable.
    sources: dict[str, dict] = {}
    for g in doc.get("grammar", []):
        src = g.get("source", {})
        if "git" in src:
            sources[g["name"]] = src

    # grammar name -> the extensions of every language that uses it (a language's
    # `grammar` defaults to its own name).
    exts: dict[str, list[str]] = {name: [] for name in sources}
    for lang in doc.get("language", []):
        grammar = lang.get("grammar", lang["name"])
        if grammar not in sources:
            continue
        for ft in lang.get("file-types", []):
            # file-types may hold {glob = ...} tables; only plain extensions map.
            if isinstance(ft, str) and ft not in exts[grammar]:
                exts[grammar].append(ft)

    return [
        {
            "name": name,
            "repo": sources[name]["git"],
            "rev": sources[name].get("rev", ""),
            "subpath": sources[name].get("subpath", ""),
            "exts": exts[name],
        }
        for name in sorted(sources)
    ]


def c_string(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def write_header(path: str, registry: list[dict]) -> None:
    lines = [
        "/* The syntax plugin's language registry — GENERATED by tools/gen-languages.py.",
        " *",
        f" * Parsed down from helix-editor/helix languages.toml @ {HELIX_REF[:12]}",
        f" * ({HELIX_LABEL}, MPL-2.0). Do not edit; re-run the generator.",
        " *",
        " * Committed, because a fresh clone has to build the plugin without running it. The",
        " * grammars themselves are NOT here: `:ring grammars` lists these and its `enter` row",
        " * builds one with tools/oket-grammar, which is what keeps a release small.",
        " */",
        "#ifndef OKET_LANGUAGES_H",
        "#define OKET_LANGUAGES_H",
        "",
        "typedef struct {",
        "    const char *name;",
        "    const char *repo;",
        "    const char *rev;     /* empty tracks the default branch */",
        "    const char *subpath; /* empty means the grammar is at the repo root */",
        "    const char *exts;    /* comma separated, no leading dots */",
        "} oket_grammar;",
        "",
        "static const oket_grammar OKET_GRAMMARS[] = {",
    ]
    for g in registry:
        lines.append(
            "    {%s, %s, %s, %s, %s},"
            % (
                c_string(g["name"]),
                c_string(g["repo"]),
                c_string(g["rev"]),
                c_string(g["subpath"]),
                c_string(",".join(g["exts"])),
            )
        )
    lines += [
        "};",
        "",
        f"#define OKET_GRAMMAR_COUNT {len(registry)}",
        "",
        "#endif",
    ]
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def main() -> int:
    out = sys.argv[1] if len(sys.argv) > 1 else "plugins/syntax/languages.h"
    registry = build_registry(fetch_languages_toml())
    write_header(out, registry)
    print(f"  wrote {len(registry)} grammars -> {out} (helix {HELIX_LABEL})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
