#!/usr/bin/env python3
"""Unicode tables, for the kernel and for plugins.

All outputs are COMMITTED. Generated source rather than a data blob, because each compiler
folds it straight into .rodata and there is nothing to parse at startup.

    tools/gen-unicode.py

One script writes every half on purpose. The kernel lays out the grid and a plugin measures
what it writes into it; the kernel moves a cursor over a word and a plugin decides where that
word ended. Either disagreement is two views of the same line (PLAN.md §8).

Four tables, each a sorted list of inclusive ranges:

  ZERO   combining marks and formatting characters, which occupy no column
  WIDE   East Asian Wide and Fullwidth, which occupy two
  SPACE  White_Space, the class the word motions skip over
  WORD   letters, decimal digits and '_', the class a word is made of

Everything outside ZERO and WIDE is one column; everything outside SPACE and WORD is
punctuation. Deriving any of this by hand does not work: a hand-rolled width table gets the
wide ranges roughly right and misses zero-width entirely, so every combining accent eats a
cell and shifts the rest of the line.
"""
import os, sys, urllib.request

UCD = "https://www.unicode.org/Public/16.0.0/ucd/"
VERSION = "16.0.0"

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WIDTH_ODIN = os.path.join(ROOT, "src/gfx/width_table.odin")
CLASS_ODIN = os.path.join(ROOT, "src/txt/class_table.odin")
HELPERS_H = os.path.join(ROOT, "src/helpers/oket_unicode.h")


def fetch(name):
    with urllib.request.urlopen(UCD + name) as r:
        return r.read().decode("utf-8")


def parse(text, wanted):
    """-> set of codepoints whose field-1 value is in `wanted`"""
    out = set()
    for line in text.splitlines():
        line = line.split("#")[0].strip()
        if not line:
            continue
        cps, _, value = line.partition(";")
        value = value.strip()
        if value not in wanted:
            continue
        lo, _, hi = cps.strip().partition("..")
        out.update(range(int(lo, 16), int(hi or lo, 16) + 1))
    return out


def ranges(cps):
    out, cps = [], sorted(cps)
    for cp in cps:
        if out and cp == out[-1][1] + 1:
            out[-1][1] = cp
        else:
            out.append([cp, cp])
    return out


def emit_c(f, name, rs, note):
    f.write(f"\n/* {note} */\n"
            f"static const oket_crange {name}[{len(rs)}] = {{\n")
    for lo, hi in rs:
        f.write(f"    {{0x{lo:04X}, 0x{hi:04X}}},\n")
    f.write("};\n")


def emit(f, name, rs, note):
    # A variable, not a constant: a `::` array is not addressable, so it cannot be sliced for
    # the binary search. @(rodata) keeps it out of .data all the same.
    f.write(f"\n// {note}\n@(rodata)\n{name} := [{len(rs)}][2]rune{{\n")
    for lo, hi in rs:
        f.write(f"    {{0x{lo:04X}, 0x{hi:04X}}},\n")
    f.write("}\n")


def main():
    if len(sys.argv) != 1:
        sys.exit(__doc__)

    cats = fetch("extracted/DerivedGeneralCategory.txt")
    eaw = fetch("EastAsianWidth.txt")
    props = fetch("PropList.txt")

    # Mn and Me are nonspacing and enclosing marks; Cf is formatting, which includes the
    # zero-width space family and the variation selectors.
    zero = parse(cats, {"Mn", "Me", "Cf"})
    zero.discard(0x00AD)          # soft hyphen: Cf, but conventionally drawn as a hyphen
    zero.update(range(0x1160, 0x1200))  # Hangul Jamo medial and final: composed onto the lead
    wide = parse(eaw, {"W", "F"})
    zero -= wide                  # nothing may be in both; zero wins for the few that overlap

    space = parse(props, {"White_Space"})
    # Nd only, not every numeric character: No holds fractions and Nl holds Roman numerals,
    # and neither reads as part of the identifier a word motion is walking.
    word = parse(cats, {"Lu", "Ll", "Lt", "Lm", "Lo", "Nd"})
    word.add(ord("_"))            # Pc, but every identifier in every language oket edits
    word -= space                 # a codepoint in both would make the class order matter

    zero_r, wide_r = ranges(zero), ranges(wide)
    space_r, word_r = ranges(space), ranges(word)

    def head_odin(pkg):
        return (f"package {pkg}\n\n"
                f"// GENERATED by tools/gen-unicode.py from Unicode {VERSION}. Do not edit.\n"
                "//\n"
                "// Committed, so a fresh clone builds without fetching anything. Re-run the\n"
                "// tool to move to a newer Unicode.\n")

    with open(WIDTH_ODIN, "w") as f:
        f.write(head_odin("gfx"))
        emit(f, "WIDTH_ZERO", zero_r,
             "Combining marks and formatting characters: no column of their own.")
        emit(f, "WIDTH_WIDE", wide_r,
             "East Asian Wide and Fullwidth: two columns.")

    with open(CLASS_ODIN, "w") as f:
        f.write(head_odin("txt"))
        emit(f, "CLASS_SPACE", space_r, "White_Space.")
        emit(f, "CLASS_WORD", word_r, "Letters, decimal digits and '_'.")

    with open(HELPERS_H, "w") as f:
        f.write(f"/* GENERATED by tools/gen-unicode.py from Unicode {VERSION}. Do not edit.\n"
                " *\n"
                " * The Odin halves of the same run are src/gfx/width_table.odin and\n"
                " * src/txt/class_table.odin. One script writes them all, because a kernel and\n"
                " * a plugin that disagree about a column lay the same line out differently, and\n"
                " * ones that disagree about a class end a word in different places.\n"
                " *\n"
                " * Included by oket_text.c and nowhere else. */\n"
                "#ifndef OKET_UNICODE_H\n"
                "#define OKET_UNICODE_H\n\n"
                "#include <stdint.h>\n\n"
                "typedef struct oket_crange {\n"
                "    uint32_t lo, hi;\n"
                "} oket_crange;\n")
        emit_c(f, "OKET_WIDTH_ZERO", zero_r,
               "Combining marks and formatting characters: no column of their own.")
        emit_c(f, "OKET_WIDTH_WIDE", wide_r, "East Asian Wide and Fullwidth: two columns.")
        emit_c(f, "OKET_SPACE_RANGES", space_r, "White_Space.")
        emit_c(f, "OKET_WORD_RANGES", word_r, "Letters, decimal digits and '_'.")
        f.write("\n#endif\n")

    for name, cps, rs in (("zero", zero, zero_r), ("wide", wide, wide_r),
                          ("space", space, space_r), ("word", word, word_r)):
        print(f"  {name:5s}: {len(cps)} codepoints in {len(rs)} ranges")
    for path in (WIDTH_ODIN, CLASS_ODIN, HELPERS_H):
        print(f"  -> {os.path.relpath(path, ROOT)}")


if __name__ == "__main__":
    main()
