#!/usr/bin/env python3
"""XKB key names -> src/input/key_table.odin.

The output is COMMITTED, same rule as gen-unicode.py: generated Odin folds into .rodata and
nothing parses at startup.

    tools/gen-keys.py src/input/key_table.odin

The source is xkeyboard-config's evdev keycodes file, the canonical map between physical
key positions and XKB names (<AC06> and friends). The numbers are X keycodes, which is the
kernel's one canonical code space: GLFW hands exactly these on X11, and evdev+8 on Wayland.

Windows (PS/2 set 1) and macOS (virtual keycodes) get their own crossmapping columns here
when those platforms land; the names stay the same.
"""
import re, sys

SRC = "/usr/share/X11/xkb/keycodes/evdev"


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    try:
        text = open(SRC).read()
    except FileNotFoundError:
        sys.exit(f"{SRC} not found — install xkeyboard-config, or fetch\n"
                 "https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/"
                 "-/raw/master/keycodes/evdev")

    codes = {}   # name -> code
    for name, num in re.findall(r"<(\w+)>\s*=\s*(\d+);", text):
        codes.setdefault(name, int(num))
    aliases = {}  # alias -> primary name
    for alias, target in re.findall(r"alias\s+<(\w+)>\s*=\s*<(\w+)>;", text):
        if target in codes:
            aliases.setdefault(alias, target)

    by_code = {}  # code -> primary name, first assignment wins; aliases never primary
    for name, code in codes.items():
        by_code.setdefault(code, name)

    pairs = sorted({**{a: codes[t] for a, t in aliases.items()}, **codes}.items())

    with open(sys.argv[1], "w") as f:
        f.write("package input\n\n"
                "// GENERATED by tools/gen-keys.py from xkeyboard-config's evdev keycodes.\n"
                "// Do not edit. Committed, so a fresh clone builds without running any tool.\n"
                "\n"
                "// Primary XKB name per code, sorted by code, for display.\n"
                "@(rodata)\n"
                f"KEY_NAMES := [{len(by_code)}]struct {{\n"
                "    code: Code,\n"
                "    name: string,\n"
                "} {\n")
        for code in sorted(by_code):
            f.write(f'    {{{code}, "{by_code[code]}"}},\n')
        f.write("}\n\n"
                "// Every name and alias, sorted by name, for the config-spelling lookup.\n"
                "@(rodata)\n"
                f"KEY_CODES := [{len(pairs)}]struct {{\n"
                "    name: string,\n"
                "    code: Code,\n"
                "} {\n")
        for name, code in pairs:
            f.write(f'    {{"{name}", {code}}},\n')
        f.write("}\n")

    print(f"  {len(by_code)} codes, {len(pairs)} names -> {sys.argv[1]}")


if __name__ == "__main__":
    main()
